/* eslint-disable @typescript-eslint/unbound-method */
import { Test, TestingModule } from '@nestjs/testing';
import { HttpException, NotFoundException } from '@nestjs/common';
import { CACHE_MANAGER } from '@nestjs/cache-manager';
import { AnalysisController } from '../../src/analysis/controllers/analysis.controller';
import { AnalysisService } from '../../src/analysis/analysis.service';
import { ScraperService } from '../../src/scraper/scraper.service';
import { JobsService } from '../../src/analysis/jobs/jobs.service';
import type { AnalysisResult } from '../../src/analysis/interfaces/analysis.types';
import type { AnalyzeJobDto } from '../../src/analysis/dto/analyze-job.dto';

// p-limit is pure ESM
jest.mock('p-limit', () => ({
  __esModule: true,
  default: jest.fn().mockReturnValue((fn: () => unknown) => fn()),
}));
jest.mock('jsdom', () => ({
  JSDOM: jest.fn().mockImplementation(() => ({ window: { document: {} } })),
}));

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

const MOCK_RESULT: AnalysisResult = {
  job: {
    title: 'Backend Engineer',
    company: 'Acme Corp',
    location: 'Berlin',
    salary: '€90k',
    skills: ['Node.js'],
    requirements: ['3+ years Node.js'],
    responsibilities: ['Build APIs'],
    remote: false,
  },
  insights: {
    competitionLevel: 'medium',
    competitionReason: 'Mid-level role with popular stack.',
    competitionConfidence: 70,
    signalsLoweringCompetition: ['Geo-locked'],
    signalsRaisingCompetition: ['Node.js', 'mid-level'],
    ghostRisk: 'low',
    ghostRiskReason: 'Salary disclosed, specific team mentioned.',
    ghostRiskConfidence: 78,
    salaryFairness: 'market',
    redFlags: [],
    positives: ['Salary disclosed'],
    verdict: { apply: true, reason: 'No major red flags.' },
  },
  strategy: {
    targetRole: 'Engineering Manager',
    contactChannels: ['LinkedIn InMail'],
    talkingPoints: ['Node.js expertise'],
    timing: 'Apply within 48 hours.',
  },
  message: {
    subject: 'Experienced Node.js engineer interested in your opening',
    body: 'Short message body.',
    tone: 'friendly',
  },
  status: 'complete',
  fallbacks: [],
  timings: {
    parseJobAndTruth: 1200,
    contactStrategy: 800,
    outreachMessage: 600,
  },
};

const URL_DTO: AnalyzeJobDto = {
  jobUrl: 'https://example.com/jobs/backend-engineer',
};

const MOCK_PARTIAL_RESULT: AnalysisResult = {
  ...MOCK_RESULT,
  status: 'partial',
  strategy: null,
  message: null,
  fallbacks: [{ step: 'contactStrategy', reason: 'AI validation failed' }],
};

// ---------------------------------------------------------------------------
// Helper — wait for the fire-and-forget pipeline to complete
// ---------------------------------------------------------------------------

/**
 * Drains the event loop so that the setImmediate pipeline callback runs and
 * all its chained promises resolve (mocks return immediately, so a single
 * setImmediate + a few microtask flushes are sufficient).
 */
async function waitForPipeline(): Promise<void> {
  await new Promise<void>((resolve) => setImmediate(resolve));
  // Drain micro-task queue generated by the async pipeline chain
  for (let i = 0; i < 20; i++) await Promise.resolve();
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('AnalysisController', () => {
  let controller: AnalysisController;
  let analysisService: jest.Mocked<AnalysisService>;
  let scraperService: jest.Mocked<ScraperService>;
  let jobsService: JobsService;
  let cacheStore: Map<string, unknown>;

  beforeEach(async () => {
    cacheStore = new Map();

    analysisService = {
      analyze: jest.fn().mockResolvedValue(MOCK_RESULT),
    } as unknown as jest.Mocked<AnalysisService>;

    scraperService = {
      fetchJobText: jest.fn().mockResolvedValue('scraped job description text'),
    } as unknown as jest.Mocked<ScraperService>;

    const mockCacheManager = {
      get: jest
        .fn()
        .mockImplementation((key: string) =>
          Promise.resolve(cacheStore.get(key) ?? null),
        ),
      set: jest.fn().mockImplementation((key: string, value: unknown) => {
        cacheStore.set(key, value);
        return Promise.resolve();
      }),
    };

    const module: TestingModule = await Test.createTestingModule({
      controllers: [AnalysisController],
      providers: [
        { provide: AnalysisService, useValue: analysisService },
        { provide: ScraperService, useValue: scraperService },
        JobsService, // real implementation — tests job lifecycle
        { provide: CACHE_MANAGER, useValue: mockCacheManager },
      ],
    }).compile();

    controller = module.get<AnalysisController>(AnalysisController);
    jobsService = module.get<JobsService>(JobsService);
  });

  afterEach(() => {
    jest.clearAllMocks();
    // Destroy JobsService timers to prevent open handles
    jobsService.onModuleDestroy();
  });

  // ── submit — input validation ───────────────────────────────────────────────

  describe('submit — input validation', () => {
    it('returns 202 with jobId and status=queued for a valid URL', async () => {
      const response = await controller.submit(URL_DTO);
      expect(response.jobId).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );
      expect(response.status).toBe('queued');
    });

    it('throws 429 when queue is at capacity', async () => {
      // Fill the queue with pending jobs by calling create() directly
      for (let i = 0; i < 50; i++) {
        jobsService.create();
      }
      await expect(controller.submit(URL_DTO)).rejects.toThrow(HttpException);
      await expect(controller.submit(URL_DTO)).rejects.toMatchObject({
        status: 429,
      });
    });
  });

  // ── getJob ────────────────────────────────────────────────────────────────

  describe('getJob', () => {
    it('returns the queued job immediately after submit', async () => {
      const { jobId } = await controller.submit(URL_DTO);
      const job = controller.getJob(jobId);
      expect(job.jobId).toBe(jobId);
      expect(['queued', 'processing']).toContain(job.status);
    });

    it('throws NotFoundException for unknown job id', () => {
      expect(() =>
        controller.getJob('00000000-0000-0000-0000-000000000000'),
      ).toThrow(NotFoundException);
    });
  });

  // ── pipeline execution ────────────────────────────────────────────────────

  describe('submit — pipeline execution', () => {
    it('transitions job to completed after pipeline runs with URL', async () => {
      const { jobId } = await controller.submit(URL_DTO);
      await waitForPipeline();

      const job = controller.getJob(jobId);
      expect(job.status).toBe('completed');
      expect(job.result).toEqual(MOCK_RESULT);
    });

    it('calls scraper when jobUrl is provided', async () => {
      await controller.submit(URL_DTO);
      await waitForPipeline();
      expect(scraperService.fetchJobText).toHaveBeenCalledWith(URL_DTO.jobUrl);
    });

    it('transitions job to failed when scraper throws', async () => {
      scraperService.fetchJobText.mockRejectedValue(
        new Error('SCRAPE_BLOCKED'),
      );
      const { jobId } = await controller.submit(URL_DTO);
      await waitForPipeline();

      const job = controller.getJob(jobId);
      expect(job.status).toBe('failed');
      expect(job.error).toContain('SCRAPE_BLOCKED');
    });

    it('transitions job to partial when analysis returns partial result', async () => {
      analysisService.analyze.mockResolvedValue(MOCK_PARTIAL_RESULT);
      const { jobId } = await controller.submit(URL_DTO);
      await waitForPipeline();

      const job = controller.getJob(jobId);
      expect(job.status).toBe('partial');
      expect(job.result?.status).toBe('partial');
      expect(job.result?.fallbacks).toHaveLength(1);
    });

    it('forwards userProfile to analysis service', async () => {
      await controller.submit({
        ...URL_DTO,
        userProfile: { role: 'Engineer' },
      });
      await waitForPipeline();
      expect(analysisService.analyze).toHaveBeenCalledWith(
        expect.objectContaining({
          userProfile: { role: 'Engineer' },
        }),
      );
    });

    it('threads jobId into the analyze call for log correlation', async () => {
      const { jobId } = await controller.submit(URL_DTO);
      await waitForPipeline();
      expect(analysisService.analyze).toHaveBeenCalledWith(
        expect.objectContaining({ jobId }),
      );
    });
  });

  // ── caching ────────────────────────────────────────────────────────────────

  describe('submit — caching', () => {
    it('returns status=completed immediately on cache hit', async () => {
      // First call to populate cache
      const first = await controller.submit(URL_DTO);
      await waitForPipeline();
      expect(controller.getJob(first.jobId).status).toBe('completed');

      // Second call — cache should be hit
      analysisService.analyze.mockClear();
      scraperService.fetchJobText.mockClear();
      const second = await controller.submit(URL_DTO);

      expect(second.status).toBe('completed');
      expect(second.result).toEqual(MOCK_RESULT);
      // Pipeline should NOT have been triggered again
      await waitForPipeline();
      expect(analysisService.analyze).not.toHaveBeenCalled();
    });

    it('uses different cache entries for different URLs', async () => {
      await controller.submit(URL_DTO);
      await controller.submit({ jobUrl: 'https://example.com/other-job' });
      await waitForPipeline();
      expect(analysisService.analyze).toHaveBeenCalledTimes(2);
    });

    it('uses different cache entries for different userProfiles', async () => {
      await controller.submit(URL_DTO);
      await controller.submit({
        ...URL_DTO,
        userProfile: { role: 'Senior Engineer' },
      });
      await waitForPipeline();
      expect(analysisService.analyze).toHaveBeenCalledTimes(2);
    });
  });
});
